# SPDX-License-Identifier: AGPL-3.0-only OR SSPL-1.0 OR Elastic-2.0
# Copyright (c) 2026 Subhrodip Mohanta (whoa.sh). All rights reserved.
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
      timezone: "UTC"
    target-branch: "master"
    open-pull-requests-limit: 10

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:15"
      timezone: "UTC"
    target-branch: "master"
    open-pull-requests-limit: 10

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:30"
      timezone: "UTC"
    target-branch: "master"
    open-pull-requests-limit: 10
